<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>$title$</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:700,400' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/normalize.css" />
    <link rel="stylesheet" href="css/app.css" />
    <script src="js/vendor/custom.modernizr.js"></script>
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">

        <div class="large-3 columns">
          <img src="images/ehrd.png"/>
        </div>

        <!-- Navigation -->
        <div class="large-9 columns">
          <ul class="button-group right">
            <li><a href="/home" class="button">Home</a></li>
            <li><a href="/meetups" class="button">Meetups</a></li>
            <li><a href="/about" class="button">About</a></li>
          </ul>
        </div>
        <hr/>
        <!-- End Navigation -->
        <div class="row">
          <!-- Main Content Section -->
          <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
          <div class="large-9 push-3 columns">

            <h3>$title$</h3>
            <p><em>(ehrd.clj)</em> is a meetup for Clojure enthustiasts in and aound Rotterdam and The Hague.
              This meetup is organized by <a href="http://vijaykiran.com">Vijay Kiran</a> and <a href="http://twitter.com/minleychris">Chris Wilson.</a>
            </p>

            <p>The name (ehrd.clj) comes from the ICAO airport code <a href="http://en.wikipedia.org/wiki/Rotterdam_The_Hague_Airport">EHRD</a> (Rotterdam/The Hague Airport).</p>

            <p>We intend to meet on the fourth Wednesday of every month for a couple of hours.  We aim to have a regular format consisting of a short talk on a Clojure library or tool, a discussion of the month's Clojure news and a main feature - maybe a talk, maybe a hack-a-long, maybe a dojo, maybe something else.</p>



            <h4>Latest Tweets</h4>
            <p class="hide-for-small">
            <a class="twitter-timeline" href="https://twitter.com/ehrdclj" data-widget-id="316865154174287873">Tweets by @ehrdclj</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </p>
          </div>


          <!-- Nav Sidebar -->
          <!-- This is source ordered to be pulled to the left on larger screens -->
          <div class="large-3 pull-9 columns">
            <div class="panel radius">
              <h5 class="subheader">Upcoming Meetup</h5>
              <h5 "subheader">27th March, 2013 19:00 - 21:30</h5>
              <h6 class="subheader"><a href="http://lunatech.com" target="_blank">Lunatech</a>, Heemraadssingel 70, Rotterdam</h6>
              <a href="http://www.meetup.com/ehrd-clj/events/104317822/" data-event="104317822"  class="small button radius alert mu-rsvp-btn">RSVP</a>
            </div>

            <div class="panel radius">
              <h5 class="subheader">Our Sponsors</h5>
              <h6>Lunatech</h6>
              <p><a href="http://lunatech.com">www.lunatech.com</a></p>
              <h6>Planspot</h6>
              <p><a href="http://planspot.com">www.planspot.com</a></p>
              <br/>
            </div>
          </div>
        </div>

        <!-- Footer -->
        <footer class="row">
          <div class="large-12 columns"><hr />
            <div class="row">
              <div class="large-4 columns">
                <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="images/cc.png" /></a>
                <small>$copyright$</small>
              </div>
              <div class="large-6 columns">
                <ul class="inline-list right">
                  <li><a href="/home">Home</a></li>
                  <li><a href="/meetups">Meetups</a></li>
                  <li><a href="/about">About</a></li>
                </ul>
              </div>
            </div>
          </div>
        </footer>
        <!-- End Footer -->
      </div>
    </div>
  </body>
</html>
