<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>$title$</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:700,400' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/normalize.css" />
    <link rel="stylesheet" href="css/app.css" />
    <script src="js/vendor/custom.modernizr.js"></script>
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">

        <div class="large-3 columns">
          <img src="images/ehrd.png"/>
        </div>

        <!-- Navigation -->
        <div class="large-9 columns">
          <ul class="button-group right">
            <li><a href="/home" class="button">Home</a></li>
            <li><a href="/blog" class="button">Blog</a></li>
            <li><a href="/meetups" class="button">Meetups</a></li>
            <li><a href="/about" class="button">About</a></li>
          </ul>
        </div>
        <hr/>
        <!-- End Navigation -->
        <div class="row">
          <!-- Nav Sidebar -->
          <!-- This is source ordered to be pulled to the left on larger screens -->
          <div class="large-3 columns hide-for-small">
            <iframe width="225" height="570" src="http://meetu.ps/N5VG8" frameborder="0"></iframe>
          </div>

          <div class="large-9 columns">
            <h3>$title$ <small>$subtitle$</small></h3>
            <div class="row right">
              <hr/>
              <h5>(init.clj) - First Meetup <small class="label secondary radius right">27-March-2013</small></h5>
                <p>On 27th March we'll have the inaugural meetup of Rotterdam/Den Haag Clojure User Group.</p>

                <p>The Agenda of the Evening: </p>
                <ul>
                  <li>Welcome - Introductions, Meet & Greet</li>
                  <li>Food & Drinks</li>
                  <li>Introducing the meetup - plans/goals/schedule</li>
                  <li>This Month in Clojure - Chris Wilson</li>
                  <li>Coffee/Tea Break</li>
                  <li>Two Talks by Christophe Grand</li>
                  <li>On to a nearest cafe for further "networking"</li>
                </ul>
            <hr />
          </div>
          
          <div class="row right">
            <h5>nth Meetup <small class="label secondary radius right">Last Wednesdays of the month</small></h5>
              <p>The Agenda of Evenings: </p>
              <ul>
                <li>Welcome - Introductions, Meet & Greet</li>
                <li>Library of the month</li>
                <li>This Month in Clojure - Chris Wilson</li>
                <li>Coffee/Tea Break</li>
                <li>Main feature</li>
                <li>Networking/Topics of Interest/Suggestions & Comments & Discussion about Meetup Planning</li>
                <li>Wrap up :-)</li>
              </ul>
          <!-- End Meetup Entry -->
        </div>

        </div>

        <!-- Footer -->
        <footer class="row">
          <div class="large-12 columns"><hr />
            <div class="row">
              <div class="large-4 columns">
                <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="images/cc.png" /></a>
                <small>$copyright$</small>
              </div>
              <div class="large-6 columns">
                <ul class="inline-list right">
                  <li><a href="/home">Home</a></li>
                  <li><a href="/blog">Blog</a></li>
                  <li><a href="/meetups">Meetups</a></li>
                  <li><a href="/about">About</a></li>
                </ul>
              </div>
            </div>
          </div>
        </footer>
        <!-- End Footer -->
      </div>
    </div>
  </body>
</html>
